# Generated by Django 2.0.5 on 2018-08-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=128)),
                ('computer_number', models.CharField(max_length=64)),
                ('computer_type', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('cab_number', models.CharField(max_length=8)),
            ],
        ),
    ]
