# Generated by Django 2.0.5 on 2018-10-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('cabinet_number', models.CharField(blank=True, default=0, max_length=8)),
            ],
            options={
                'verbose_name': 'Компютер',
                'verbose_name_plural': 'Компютери',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('military_number', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('street', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('building', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменти',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OfficersAdminsSedo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Офіцер ЦАБ',
                'verbose_name_plural': 'Офіцери ЦАБ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='SedoAllowances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_income_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('our_income_date', models.DateField(blank=True, default=None, null=True)),
                ('alien_outcome_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('alien_outcome_date', models.DateField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('CAB_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CAB_officer', to='cedoinclusion.OfficersAdminsSedo')),
                ('cyber_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cyber_user', to='cedoinclusion.Personal')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoinclusion.Departments')),
            ],
            options={
                'verbose_name': 'Включення',
                'verbose_name_plural': 'Включення',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedoinclusion.Ranks'),
        ),
        migrations.AddField(
            model_name='computers',
            name='sedo_allowance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoinclusion.SedoAllowances'),
        ),
    ]
