# Generated by Django 2.0.5 on 2018-08-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedoinclusion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('cabinet_number',),
            },
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
                'ordering': ('serial_number',),
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='SedoAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_income_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('our_income_date', models.DateField(blank=True, default=None, null=True)),
                ('alien_outcome_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('alien_outcome_date', models.DateField(blank=True, default=None, null=True)),
                ('id_sedo_allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoinclusion.Computers')),
            ],
            options={
                'ordering': ('our_income_number',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('id_cyber_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoinclusion.SedoAllowance')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Inclusion',
        ),
        migrations.AddField(
            model_name='ranks',
            name='id_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoinclusion.Users'),
        ),
        migrations.AddField(
            model_name='departments',
            name='id_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoinclusion.SedoAllowance'),
        ),
        migrations.AddField(
            model_name='cabinets',
            name='id_cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoinclusion.Computers'),
        ),
    ]
