# Generated by Django 2.0.5 on 2018-08-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedoinclusion', '0002_auto_20180828_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computers',
            options={'ordering': ('serial_number',), 'verbose_name': 'Компютер', 'verbose_name_plural': 'Компютери'},
        ),
    ]
