# Generated by Django 2.0.5 on 2018-08-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedoinclusion', '0006_auto_20180828_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresses',
            name='building',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='adresses',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='adresses',
            name='id_adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoinclusion.Departments'),
        ),
    ]
